db:
  host: "172.31.26.109"
  username: "application"
  db: "appdb"
  password: "applicationP@33word"

validation_api:
  1: "http://10.0.153.141:8002/detection/yolov5/validate"
  4: "http://10.0.153.141:8003/detection/tensorflow/validate"
  2: "http://10.0.153.141:8001/detection/yolov8/validate"
  3: "http://10.0.153.141:8004/detection/paddleocr/validate"

