db:
  host: "172.16.0.214"
  username: "vishal"
  db: "tcl-uat"
  password: "Welcome#123"

validation_api:
  1: "http://172.16.0.204:8002/detection/yolov5/validate"
  4: "http://172.16.0.204:8003/detection/tensorflow/validate"
  2: "http://172.16.0.204:8001/detection/yolov8/validate"
  3: "http://172.16.0.204:8004/detection/paddleocr/validate"
